### ISSUE TITLE
A wrong user id has been provided.

### ISSUE THREAD

**Issue by dekulol1212** [MASSKAgithub/Youtube-SHOUTOUT-WALL#1]
Whenever I attempt to add my channel manually on the list for testing and insert my youtube channel id into "https://test.glitch.me/add?id=$(userid)" it never works, the output is "A wrong user id has been provided." I haven't tried live streaming it yet, as I have to wait 24 hours.
Note: the https://test.glitch.me website is not actually mine and has just been used as an example
If there is another way into manually adding my username on the list, please tell me!

**Comment by MASSKAgithub** [comment]
Hello,

When you add the userid are you sure to replace the $(userid) by your ID? do you use a custom url ID or the automatic string of integers that each youtube channel has? Did you remove the dollar and the parathensice symbols too?


This code is really old I posted it more than a year after I finished it so there are good chances that google has updated their API and it could be problematic.

**Comment by dekulol1212** [comment]
> Hello,
> 
> When you add the userid are you sure to replace the $(userid) by your ID? do you use a custom url ID or the automatic string of integers that each youtube channel has? Did you remove the dollar and the parathensice symbols too?
> 
> This code is really old I posted it more than a year after I finished it so there are good chances that google has updated their API and it could be problematic.

Yeah, it's understandable. I did remove both and I use the string of integers, you don't need to reply to this if you don't want to, but this was the only actual good post that I could find and it seems to be sort of working, I just saw these YouTube shoutout wall live spams and I thought it would be cool if I made my own without publishing it and testing it out for bugs and just for fun. If there are other posts like yours even on external platforms then please send me links or posts.

**Comment by dekulol1212** [comment]
Hello, I made a mistake on trying to add it manually, I didn't remove the brackets.
Ah well, I am so sorry.
Thanks for your help!
